apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: <your_root_password> # Replace with base64 encoded password
  MYSQL_DATABASE: <your_database_name> # Replace with base64 encoded database name
  MYSQL_USER: <your_username> # Replace with base64 encoded username
  MYSQL_PASSWORD: <your_password> # Replace with base64 encoded password